### ISSUE TITLE
Could you provide some basic infrastructure that would work with this?

### ISSUE THREAD

**Issue by PianoPenguin471** [sebvstian/VapeLite-ClickGui#1]
Could you provide some basic infrastructure that would work with this? For example, a module class and options?

**Comment by 0xSebastian** [comment]
Here is a example Module (ESP): https://hastebin.skyra.pw/xewejimugu.ts

**Comment by HHuxy7** [comment]
Can you repost this https://hastebin.skyra.pw/xewejimugu.ts for me its empty

**Comment by sebvstian** [comment]
Late but here is the esp sorry https://pastebin.com/ZBJqWY4r
